# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        8,
        _('Provinces'),
        ['lineasDepto'],
        [],
[
    (_('North Eastern'), ''),
	(_('North Central'), ''),
	(_('North Western'), ''),
	(_('Central'), ''),
	(_('Eastern'), ''),
	(_('Uva'), ''),
	(_('Western'), ''),
	(_('Sabaragamuwa'), ''),
	(_('Southern'), '')
]
]

LEVEL2 = [
        2,
        _('Provincial capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
	(_('Sri Jayewardenepura Kotte'), _("It's the capital of Sri Lanka")),
    (_('Galle'), _("It's in %s") % _('Southern')),
	(_('Ratnapura'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Colombo'), _("It's in %s") % _('Western')),
	(_('Anuradhapura'), _("It's in %s") % _('North Central')),
	(_('Badulla'), _("It's in %s") % _('Uva')),
	(_('Batticaloa'), _("It's in %s") % _('Eastern')),
	(_('Kandy'), _("It's in %s") % _('Central')),
	(_('Kurunegala'), _("It's in %s") % _('North Western')),
	(_('Jaffna'),_("It's in %s") % _('North Eastern'))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
	(_('Sri Jayewardenepura Kotte'), _("It's the capital of Sri Lanka")),
    (_('Galle'), _("It's in %s") % _('Southern')),
	(_('Ratnapura'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Colombo'), _("It's in %s") % _('Western')),
	(_('Anuradhapura'), _("It's in %s") % _('North Central')),
	(_('Badulla'), _("It's in %s") % _('Uva')),
	(_('Batticaloa'), _("It's in %s") % _('Eastern')),
	(_('Kandy'), _("It's in %s") % _('Central')),
	(_('Kurunegala'), _("It's in %s") % _('North Western')),
	(_('Jaffna'),_("It's in %s") % _('North Eastern')),
	(_('Kankesanturai'), _("It's in %s") % _('North Eastern')),
	(_('Point Pedro'), _("It's in %s") % _('North Eastern')),
	(_('Kayts'), _("It's in %s") % _('North Eastern')),
	(_('Elephant Pass'), _("It's in %s") % _('North Eastern')),
	(_('Kilinochchi'), _("It's in %s") % _('North Eastern')),
	(_('Mullaittivu'), _("It's in %s") % _('North Eastern')),
	(_('Puthukkudiyiruppu'), _("It's in %s") % _('North Eastern')),
	(_('Vellankulam'), _("It's in %s") % _('North Eastern')),
	(_('Manjulam'), _("It's in %s") % _('North Eastern')),
	(_('Nedunkeni'), _("It's in %s") % _('North Eastern')),
	(_('Puliyankulam'), _("It's in %s") % _('North Eastern')),
	(_('Vavuniya'), _("It's in %s") % _('North Eastern')),
	(_('Madhu Road'), _("It's in %s") % _('North Eastern')),
	(_('Talaimannar'), _("It's in %s") % _('North Eastern')),
	(_('Mannar'), _("It's in %s") % _('North Eastern')),
	(_('Silavatturai'), _("It's in %s") % _('North Eastern')),
	(_('Pulmoddai'), _("It's in %s") % _('Eastern')),
	(_('Pankulam'), _("It's in %s") % _('Eastern')),
	(_('Nilaveli'), _("It's in %s") % _('Eastern')),
	(_('Trincomalee'), _("It's in %s") % _('Eastern')),
	(_('Horuwupotana'), _("It's in %s") % _('North Central')),
	(_('Kebitigollewa'), _("It's in %s") % _('North Central')),
	(_('Medawachchiya'), _("It's in %s") % _('North Central')),
	(_('Hamillewa'), _("It's in %s") % _('North Central')),
	(_('Pomparippu'), _("It's in %s") % _('North Western')),
	(_('Kalpitiya'), _("It's in %s") % _('North Western')),
	(_('Puttalam'), _("It's in %s") % _('North Western')),
	(_('Maragahewa'), _("It's in %s") % _('North Central')),
	(_('Kekirawa'), _("It's in %s") % _('North Central')),
	(_('Habarane'), _("It's in %s") % _('North Central')),
	(_('Galgamuwa'), _("It's in %s") % _('North Western')),
	(_('Mutur'), _("It's in %s") % _('Eastern')),
	(_('Kantalai'), _("It's in %s") % _('Eastern')),
	(_('Kathiraveli'), _("It's in %s") % _('Eastern')),
	(_('Polonnaruwa'), _("It's in %s") % _('North Central')),
	(_('Valachchenai'), _("It's in %s") % _('Eastern')),
	(_('Chenkaladi'), _("It's in %s") % _('Eastern')),
	(_('Dambula'), _("It's in %s") % _('Central')),
	(_('Naula'), _("It's in %s") % _('Central')),
	(_('Anamaduwa'), _("It's in %s") % _('North Western')),
	(_('Maho'), _("It's in %s") % _('North Western')),
	(_('Ganewatta'), _("It's in %s") % _('North Western')),
	(_('Chilaw'), _("It's in %s") % _('North Western')),
	(_('Kuliyapitiya'), _("It's in %s") % _('North Western')),
	(_('Maha Oya'), _("It's in %s") % _('Eastern')),
	(_('Paddiruppu'), _("It's in %s") % _('Eastern')),
	(_('Kehelula'), _("It's in %s") % _('Eastern')),
	(_('Kalmunai'), _("It's in %s") % _('Eastern')),
	(_('Uhana'), _("It's in %s") % _('Eastern')),
	(_('Amparai'), _("It's in %s") % _('Eastern')),
	(_('Mahiyangana'), _("It's in %s") % _('Central')),
	(_('Tirrukkovil'), _("It's in %s") % _('Eastern')),
	(_('Bibile'), _("It's in %s") % _('Uva')),
	(_('Pottuvil'), _("It's in %s") % _('Eastern')),
	(_('Monaragala'), _("It's in %s") % _('Uva')),
	(_('Okanda'), _("It's in %s") % _('Eastern')),
	(_('Buttala'), _("It's in %s") % _('Uva')),
	(_('Matale'), _("It's in %s") % _('Central')),
	(_('Pannala'), _("It's in %s") % _('North Western')),
	(_('Negombo'), _("It's in %s") % _('Western')),
	(_('Kegalla'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Gampaha'), _("It's in %s") % _('Western')),
	(_('Ja-Ela'), _("It's in %s") % _('Western')),
	(_('Avissawella'), _("It's in %s") % _('Western')),
	(_('Nuwara Eliya'), _("It's in %s") % _('Central')),
	(_('Haputale'), _("It's in %s") % _('Uva')),
	(_('Balangoda'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Tellula'), _("It's in %s") % _('Uva')),
	(_('Kumana'), _("It's in %s") % _('Eastern')),
	(_('Kataragama'), _("It's in %s") % _('Uva')),
	(_('Embilipitiya'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Tissamaharama'), _("It's in %s") % _('Southern')),
	(_('Kirinda'), _("It's in %s") % _('Southern')),
	(_('Hambontota'), _("It's in %s") % _('Southern')),
	(_('Moratuwa'), _("It's in %s") % _('Western')),
	(_('Panadura'), _("It's in %s") % _('Western')),
	(_('Horana'), _("It's in %s") % _('Western')),
	(_('Kalutara'), _("It's in %s") % _('Western')),
	(_('Beruwala'), _("It's in %s") % _('Western')),
	(_('Pelmadulla'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Matugama'), _("It's in %s") % _('Western')),
	(_('Rakwana'), _("It's in %s") % _('Sabaragamuwa')),
	(_('Deniyaya'), _("It's in %s") % _('Southern')),
	(_('Ambalangoda'), _("It's in %s") % _('Southern')),
	(_('Udugama'), _("It's in %s") % _('Southern')),
	(_('Akuressa'), _("It's in %s") % _('Southern')),
	(_('Tangalla'), _("It's in %s") % _('Southern')),
	(_('Matara'), _("It's in %s") % _('Southern'))
]
]


LEVELS = [LEVEL1, LEVEL2, LEVEL3]

